name: panache_ui
description: A new Flutter project.
version: 0.0.1
author:
homepage:
publish_to: none

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  panache_core:
    path: ../panache_core

  provider: ^5.0.0

  #panache_services:
    #path: ../panache_services

dev_dependencies:
  effective_dart:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - github.png
